name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master
    release:
        types: [ published ]
    workflow_dispatch:

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
    pipeline:
        uses: oberon-oss/github-workflows/.github/workflows/maven-pipeline.yml@8b4d9042dc4700b2da328dcce9e30dca3e617997
        with:
            java-version: '25'
            profiles: 'lombok,jacoco'
            deploy-profiles: 'lombok,activate-oberon-nexus'
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
            NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}