name: CI/CD Pipeline

on:
    push:
        branches-ignore:
            - 'main'
            - 'master'
    pull_request:
        branches:
            - 'main'
            - 'master'
    release:
        types: [ published ]
    workflow_dispatch:

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
    pipeline:
        uses: oberon-oss/github-workflows/.github/workflows/maven-pipeline.yml@c299eeb0f905b62e66c4abe6b308856d96e39713
        with:
            java-version: '25'
            profiles: 'lombok,jacoco'
            deploy-profiles: 'lombok,activate-oberon-nexus'
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
            NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}