name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    release:
        types: [ published ]
    workflow_dispatch:

permissions:
    contents: read
    packages: write
    id-token: write
    pages: write

jobs:
    pipeline:
        uses: oberon-oss/github-workflows/.github/workflows/maven-pipeline.yml@340885244b67a4771510fccd5807cdc3a33bc9f2
        with:
            java-version: '25'
            profiles: 'lombok,jacoco'
            deploy-profiles: 'lombok,activate-oberon-nexus'
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
            NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}