name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - master
        tags:
            - 'v*.*.*'
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    pipeline:
        uses: oberon-oss/github-workflows/.github/workflows/maven-pipeline.yml@v2.0.5
        with:
            profiles: 'lombok'
        secrets:
            NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
            NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}